SIPNET: testEventInfra.c File Reference
testEventInfra.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "modelStructures.h"
#include "utils/tUtils.h"
#include "sipnet/events.c"
Functions
int checkEvent (EventNode *event, int loc, int year, int day, enum EventType type)
int checkHarvestParams (HarvestParams *params, double fracRemAbove, double fracRemBelow, double fracTransAbove, double fracTransBelow)
int checkIrrigationParams (IrrigationParams *params, double amountAdded, int method)
int checkFertilizationParams (FertilizationParams *params, double orgN, double orgC, double minN)
int checkPlantingParams (PlantingParams *params, int emergenceLag, double addedC, double addedN)
int checkTillageParams (TillageParams *params, double fracLitterTransferred, double somDecompModifier, double litterDecompModifier)
int init (void)
int runTestEmpty (void)
int runTestSimple (void)
int runTestMulti (void)
int run (void)
void cleanup (void)
int main (void)
Function Documentation
checkEvent()
int checkEvent (EventNode * event, int loc, int year, int day, enum EventType type)
Definition at line 9 of file testEventInfra.c.
References printEvent().
Referenced by runTestMulti(), and runTestSimple().
checkFertilizationParams()
int checkFertilizationParams (FertilizationParams * params, double orgN, double orgC, double minN)
Definition at line 39 of file testEventInfra.c.
References compareDoubles(), and params.
Referenced by runTestMulti(), and runTestSimple().
checkHarvestParams()
int checkHarvestParams (HarvestParams * params, double fracRemAbove, double fracRemBelow, double fracTransAbove, double fracTransBelow)
Definition at line 24 of file testEventInfra.c.
References compareDoubles(), and params.
Referenced by runTestMulti(), and runTestSimple().
checkIrrigationParams()
int checkIrrigationParams (IrrigationParams * params, double amountAdded, int method)
Definition at line 33 of file testEventInfra.c.
References compareDoubles(), and params.
Referenced by runTestMulti(), and runTestSimple().
checkPlantingParams()
int checkPlantingParams (PlantingParams * params, int emergenceLag, double addedC, double addedN)
Definition at line 46 of file testEventInfra.c.
References compareDoubles(), and params.
Referenced by runTestMulti(), and runTestSimple().
checkTillageParams()
int checkTillageParams (TillageParams * params, double fracLitterTransferred, double somDecompModifier, double litterDecompModifier)
Definition at line 53 of file testEventInfra.c.
References compareDoubles(), and params.
Referenced by runTestMulti(), and runTestSimple().
cleanup()
void cleanup (void)
Definition at line 208 of file testEventInfra.c.
Referenced by main().
init()
int init (void)
Definition at line 61 of file testEventInfra.c.
main()
int main (void)
Definition at line 213 of file testEventInfra.c.
References cleanup(), exit(), and run().
run()
int run (void)
Definition at line 186 of file testEventInfra.c.
References runTestEmpty(), runTestMulti(), and runTestSimple().
Referenced by main().
runTestEmpty()
int runTestEmpty (void)
Definition at line 63 of file testEventInfra.c.
References numLocs, and readEventData().
Referenced by run().
runTestMulti()
int runTestMulti (void)
Definition at line 109 of file testEventInfra.c.
References checkEvent(), checkFertilizationParams(), checkHarvestParams(), checkIrrigationParams(), checkPlantingParams(), checkTillageParams(), FERTILIZATION, HARVEST, IRRIGATION, numLocs, PLANTING, readEventData(), and TILLAGE.
Referenced by run().
runTestSimple()
int runTestSimple (void)
Definition at line 75 of file testEventInfra.c.
References checkEvent(), checkFertilizationParams(), checkHarvestParams(), checkIrrigationParams(), checkPlantingParams(), checkTillageParams(), FERTILIZATION, HARVEST, IRRIGATION, numLocs, PLANTING, readEventData(), and TILLAGE.
Referenced by run().