site_name: SIPNET Documentation

nav:
  - Home: README.md
  - Parameters: parameters.md
  - Model Specification: model-specification.md
  - User Guide:
      - Running SIPNET: user-guide/running-sipnet.md
  - Developer Guide:
      - Code Structure: developer-guide/code-structure.md
  - Contributing: CONTRIBUTING.md
  - API Reference: api/index.html
  - Changelog: CHANGELOG.md
  - Code of Conduct: CODE_OF_CONDUCT.md

theme:
  name: readthedocs

plugins:
  - search
  - mathjax



