SIPNET: testEventIrrigation.c File Reference
testEventIrrigation.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "modelStructures.h"
#include "utils/tUtils.h"
#include "sipnet/sipnet.c"
Functions
int checkOutput (double soilWater, double immedEvap)
int run ()
int main ()
Function Documentation
checkOutput()
int checkOutput (double soilWater, double immedEvap)
Definition at line 9 of file testEventIrrigation.c.
References compareDoubles(), envi, fluxes, FluxVars::immedEvap, and Environment::soilWater.
Referenced by run().
main()
int main (void)
Definition at line 62 of file testEventIrrigation.c.
References exit(), and run().
run()
int run (void)
Definition at line 24 of file testEventIrrigation.c.
References checkOutput(), climate, ClimateVars::day, envi, fluxes, FluxVars::immedEvap, Parameters::immedEvapFrac, numLocs, params, readEventData(), Environment::soilWater, and ClimateVars::year.
Referenced by main().