SIPNET: testEventInfraNeg.c File Reference
testEventInfraNeg.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "modelStructures.h"
#include "sipnet/events.c"
#include "utils/exitHandler.c"
Functions
int run ()
int main ()
Function Documentation
main()
int main ()
Definition at line 91 of file testEventInfraNeg.c.
References exit(), and run().
run()
int run ()
Definition at line 9 of file testEventInfraNeg.c.
References EXIT_CODE_INPUT_FILE_ERROR, EXIT_CODE_UNKNOWN_EVENT_TYPE_OR_PARAM, exit_result, expected_code, jump_env, readEventData(), really_exit, should_exit, and test_assert.
Referenced by main().