SIPNET: namelistInput.c File Reference
namelistInput.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include "namelistInput.h"
#include "util.h"
Functions
NamelistInputItem * newNamelistInputItem (char *name, int type, void *ptr, int maxlen)
NamelistInputItem * locateNamelistInputItem (NamelistInputs *namelistInputs, char *name)
NamelistInputs * newNamelistInputs ()
void addNamelistInputItem (NamelistInputs *namelistInputs, char *name, int type, void *ptr, int maxlen)
void readNamelistInputs (NamelistInputs *namelistInputs, const char *fileName)
void dieIfNotRead (NamelistInputs *namelistInputs, char *name)
void dieIfNotSet (NamelistInputs *namelistInputs, char *name)
void deleteNamelistInputs (NamelistInputs *namelistInputs)
Function Documentation
addNamelistInputItem()
void addNamelistInputItem (NamelistInputs * namelistInputs, char * name, int type, void * ptr, int maxlen)
Definition at line 90 of file namelistInput.c.
References NamelistInputsStruct::count, newNamelistInputItem(), NamelistInputItemStruct::nextItem, and NamelistInputsStruct::tail.
Referenced by main().
deleteNamelistInputs()
void deleteNamelistInputs (NamelistInputs * namelistInputs)
Definition at line 261 of file namelistInput.c.
References NamelistInputsStruct::head, and NamelistInputItemStruct::nextItem.
dieIfNotRead()
void dieIfNotRead (NamelistInputs * namelistInputs, char * name)
Definition at line 216 of file namelistInput.c.
References exit(), locateNamelistInputItem(), and NamelistInputItemStruct::wasRead.
Referenced by dieIfNotSet(), and main().
dieIfNotSet()
void dieIfNotSet (NamelistInputs * namelistInputs, char * name)
Definition at line 238 of file namelistInput.c.
References dieIfNotRead(), exit(), locateNamelistInputItem(), NamelistInputItemStruct::ptr, STRING_TYPE, and NamelistInputItemStruct::type.
Referenced by main().
locateNamelistInputItem()
NamelistInputItem * locateNamelistInputItem (NamelistInputs * namelistInputs, char * name)
Definition at line 51 of file namelistInput.c.
References NamelistInputsStruct::head, NamelistInputItemStruct::name, NamelistInputItemStruct::nextItem, and strcmpIgnoreCase().
Referenced by dieIfNotRead(), dieIfNotSet(), and readNamelistInputs().
newNamelistInputItem()
NamelistInputItem * newNamelistInputItem (char * name, int type, void * ptr, int maxlen)
Definition at line 26 of file namelistInput.c.
References exit(), NamelistInputItemStruct::maxlen, NamelistInputItemStruct::name, NAMELIST_INPUT_MAXNAME, NamelistInputItemStruct::nextItem, NamelistInputItemStruct::ptr, NamelistInputItemStruct::type, and NamelistInputItemStruct::wasRead.
Referenced by addNamelistInputItem(), and newNamelistInputs().
newNamelistInputs()
NamelistInputs * newNamelistInputs ()
Definition at line 70 of file namelistInput.c.
References NamelistInputsStruct::count, NamelistInputsStruct::head, newNamelistInputItem(), and NamelistInputsStruct::tail.
Referenced by main().
readNamelistInputs()
void readNamelistInputs (NamelistInputs * namelistInputs, const char * fileName)
Definition at line 112 of file namelistInput.c.
References DOUBLE_TYPE, exit(), INT_TYPE, locateNamelistInputItem(), LONG_TYPE, NamelistInputItemStruct::maxlen, openFile(), NamelistInputItemStruct::ptr, SEPARATORS, STRING_TYPE, stripComment(), NamelistInputItemStruct::type, and NamelistInputItemStruct::wasRead.
Referenced by main().