name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:

  # try to build PEcAn on all versions of R
  build:
    strategy:
      fail-fast: false
      matrix:
        OS:
          - macos-latest
          - ubuntu-latest
          - ubuntu-20.04
          - windows-latest

    runs-on: ${{ matrix.OS }}

    steps:
    # checkout source code
    - uses: actions/checkout@v2

    # compile sipnet
    - name: compile sipnet
      run: make

    # remove existing test output file
    - name: Remove File
      uses: JesseTG/rm@v1.0.3
      with:
        path: Sites/Niwot/niwot.out

    # run single sipnet run
    - name: sipnet on Sites/Niwot/niwot
      run: ./sipnet

    # check output of test
    - name: fail if no niwot output exists
      if: ${{ hashFiles('Sites/Niwot/niwot.out') == '' }}
      run: |
        echo "::error title={No Output}::Test run for Niwot site failed to produce output"
        exit 1
