name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:

  # try to build SIPNET on Windows, Ubuntu, MacOS
  build:
    strategy:
      fail-fast: false
      matrix:
        OS:
          - macos-latest
          - ubuntu-latest
          - ubuntu-20.04
          - windows-latest

    runs-on: ${{ matrix.OS }}

    steps:
    # checkout source code
    - uses: actions/checkout@v2

    # compile sipnet
    - name: compile sipnet
      run: make

    # remove existing test output file
    - name: Remove Niwout Output File
      run: rm Sites/Niwot/niwot.out

    # run single sipnet run
    - name: sipnet on Sites/Niwot/niwot
      run: ./sipnet

    # check output of test
    - name: fail if no niwot output exists
      if: ${{ hashFiles('Sites/Niwot/niwot.out') == '' }}
      run: |
        echo "::error title={No Output}::Test run for Niwot site failed to produce output"
        exit 1
    # check whether niwot.out has changed
    - name: Check whether niwot.out has changed 
      if: runner.os != 'Windows' #fails b/c line endings?
      shell: bash
      run: |
         if git diff --exit-code Sites/Niwot/niwot.out; then
           echo "Success: Niwot.out created and has not changed"
           else
             echo "::error title={Output Changed}::The test file niwot.out has changed"
           exit 1
           fi
